version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: taskmanagement_postgres
    environment:
      POSTGRES_DB: task_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: task_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres