spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret: mysecretkeymysecretkeymysecretkey123456
  expiration: 86400000